### ISSUE TITLE
M2 - 1. Observe - The Core Skill Focus of the Week Framework 

### ISSUE THREAD

**Issue by psjiranek** [kneesen22/Deeper_Dive#12]
Where it fits in the weekly routine?
The Core Skill Focus of the Week Framework encourages observations at the start of each week.

Educators will:

1. Use the Core Skill Summary Sheet to learn more about the Subskill of the week.
2. Observe that skill and take quick notes across the day as children engage in different activities.

**I am a little confused about the Core Skill Focus of the Week and the Subskill from 1#. In #2., does "that skill" refer to the Core Skill or the Subskill. Should #2 refer to "that Subskill" instead? I realize that would mean changing other references, however.** 

https://educationvirginia.instructure.com/courses/13526/pages/1-observe-the-core-skill-focus-of-the-week-framework

**Comment by kneesen22** [comment]
I will change it to subskill in #2
