### ISSUE TITLE
M2 - 6. Combatting Biases in Your Observations

### ISSUE THREAD

**Issue by psjiranek** [kneesen22/Deeper_Dive#13]
1) Seems like these should match:

  6. Combatting Biases in Your Observations
  Confronting Biases in Observations

2) In the Observation Strategies graphic, there's a period missing in the top right blue box: "Share observation load..."

https://educationvirginia.instructure.com/courses/13526/pages/6-combatting-biases-in-your-observations

**Comment by kneesen22** [comment]
Second title removed for now. Text reworked slightly. Leaving image correction for stephanie W.

**Comment by kneesen22** [comment]
@walkersb2 one small period to address in the image on this page for you.

**Comment by walkersb2** [comment]
Period added to the image. Text was updated with suggestions to integrate the reading; however, I'm waiting to hear back from Stephanie A. to confirm that she wanted the call to the reading to happen first on the page instead of later.
