### ISSUE TITLE
M4 1. FOCUS: The Core Skill Focus of the Week Framework

### ISSUE THREAD

**Issue by psjiranek** [kneesen22/Deeper_Dive#14]
In the graphic under Where it fits in the weekly routine? under Tuesday FOCUS, the "For example,..." part isn't a complete sentence. It could be incorporated into the first sentence?

https://educationvirginia.instructure.com/courses/13526/pages/1-focus-the-core-skill-focus-of-the-week-framework/edit

**Comment by kneesen22** [comment]
Part of the curriculum and cannot be altered.
