### ISSUE TITLE
M4 2. Labeling, Modeling, and Narrating

### ISSUE THREAD

**Issue by psjiranek** [kneesen22/Deeper_Dive#15]
Under Narrating, the video stops halfway through and shows an ad for velcro pull-apart fruit! The "educator" also refers to herself as "Mommy" so that seemed a little odd to use as an example. And the text below seems awkward to just say "their efforts" without mentioning the child?

Notice how this educator narrates by talking about their efforts to pull the toy apart.

https://educationvirginia.instructure.com/courses/13526/pages/2-labeling-modeling-and-narrating?module_item_id=395003

**Comment by kneesen22** [comment]
The video is supposed to stop at 2 minutes and we can't control the way the ads from Youtube appear at that point. I will check with Stephanie A about the use of their. The their is referencing the parent's action.

**Comment by psjiranek** [comment]
The ad popped up in the middle and the video stopped playing, so there was more to the video afterwards. Is there a way for the video to run the full length before the ads come?

Also, I think it's a little funny to say "Notice how this educator..." when it's the mom?

**Comment by kneesen22** [comment]
changed sentence to: Notice how this adult narrates by talking about the child’s efforts to pull the toy apart.
