### ISSUE TITLE
Core Skill Summary Sheet

### ISSUE THREAD

**Issue by psjiranek** [kneesen22/Deeper_Dive#2]
Core Skill Summary Sheet

if you click the link to see the descriptive answer guide, it's called Core Skills Sheet. Should Core Skills be plural when you reference Core Skill Summary Sheet other places? 

https://educationvirginia.instructure.com/courses/13526/pages/2a-you-explore-page-1-of-the-core-skill-summary-sheet/edit

**Comment by kneesen22** [comment]
It should be called Core Skill Summary Sheet wherever it is referenced.

**Comment by walkersb2** [comment]
Fixed.
