### ISSUE TITLE
Self-Care and Healthy Habits Through Books

### ISSUE THREAD

**Issue by psjiranek** [kneesen22/Deeper_Dive#25]
Self-Care and Healthy Habits Through Books
Engaging stories that encourage children to explore healthy foods and take on tasks with increasing independence

seems like the subhead should say something like "self-care tasks" ?

https://eceresourcehub.org/ece-resource-hub/book-collections/supporting-self-care-and-healthy-habits-through-books/

**Comment by kneesen22** [comment]
done
