### ISSUE TITLE
Self-Care and Healthy Habits Through Books

### ISSUE THREAD

**Issue by psjiranek** [kneesen22/Deeper_Dive#26]
Young children are learning how to take responsibility for their self-care and are developing healthy eating habits. These books are a great way to show children different ways they can take care of their bodies by participating in daily routines and eating nutritious foods.

change "great way" to "great resource" or something so way/ways don't get repeated in the 2nd sentence? 

https://eceresourcehub.org/ece-resource-hub/book-collections/supporting-self-care-and-healthy-habits-through-books/

**Comment by kneesen22** [comment]
done. good catch
