### ISSUE TITLE
FEATURED BOOKS - PRESCHOOL

### ISSUE THREAD

**Issue by psjiranek** [kneesen22/Deeper_Dive#27]
Today
1. book photo should have cover picture so title is there (it's on this webpage: https://juliemorstad.com/BOOKS)

the Pigeon Needs a Bath!
Written and illustrated by Mo Willems, this book shows the journey of a silly and reluctant pigeon as they learn to have fun washing and getting clean.
2. Capitalize The in title
3. change "as they learn" to "as it learns".

Amara's Farm
Written by JaNay Brown 
4. author's name is Brown-Wood

Tomatoes for Neela 
5. cover photo on this page: https://www.penguinrandomhouse.com/books/625181/tomatoes-for-neela-by-padma-lakshmi-illustrated-by-juana-martinez-neal/

Written by Padma Lakshmi and illustrated by Juana Martinez-Neal, this story shows a child connecting with her family by learning about and cooking the food that nourishes them.
6. "shows a child connecting with her family as she learns about..."?

https://eceresourcehub.org/ece-resource-hub/book-collections/supporting-self-care-and-healthy-habits-through-books/

**Comment by kneesen22** [comment]
changes made
