### ISSUE TITLE
1. SCAFFOLD: The Core Skill Focus of the Week Framework

### ISSUE THREAD

**Issue by psjiranek** [kneesen22/Deeper_Dive#37]
Scaffold: What is it?
Educators scaffold children to support their development of Core Skills.

They provide support and feedback that allows children to perform at a higher level than they would independently.

I'm wondering if "allows" should actually be "allow" since it's referring to "support AND feedback"?

https://educationvirginia.instructure.com/courses/13526/pages/1-scaffold-the-core-skill-focus-of-the-week-framework?module_item_id=394988

**Comment by kneesen22** [comment]
i agree..changed
