### ISSUE TITLE
M5 

### ISSUE THREAD

**Issue by psjiranek** [kneesen22/Deeper_Dive#39]
I tried to find more examples to see what's preferred between Infant/Toddler and Infant - Toddler Curriculum but decided just to ask here!

from the page 1: Where it fits in the weekly routine?
Educators ...
In the Infant/Toddler Curriculum,
https://educationvirginia.instructure.com/courses/13526/pages/1-scaffold-the-core-skill-focus-of-the-week-framework?module_item_id=394988

from page 3: What to Expect With Scaffolding Suggestions: 
Scaffolding suggestions appear...
They appear most weeks in the Infant - Toddler Curriculum when developmentally appropriate.
https://educationvirginia.instructure.com/courses/13526/pages/3-you-explore-scaffold-resources-on-the-csfow-summary-sheet?module_item_id=399047

**Comment by kneesen22** [comment]
checking on this

**Comment by kneesen22** [comment]
changed to infant-toddler
