### ISSUE TITLE
TYK 5

### ISSUE THREAD

**Issue by psjiranek** [kneesen22/Deeper_Dive#40]
TYK.5 0.2 pts
Which of the following definitions best defines visuals?

  Transitions between activities and routines. 
Incorrect. While this observation is behavioral, it’s not objective. It’s behavioral because it specifically describes what happened (e.g., "had different children come up to count the days of the month").  This observation isn’t objective because it includes observations that are subjective/judgmental: "great job," "I love," "fun," and "nice job." These are personal feelings, interpretations, or biases instead of what actually happened in the classroom.

Answer option 1 - the Incorrect response is Incorrect!! I replaced it with the Incorrect response from the other choice but wanted to be sure that was COrrect.

https://educationvirginia.instructure.com/courses/13526/quizzes/27540/edit

**Comment by kneesen22** [comment]
looks good...
