### ISSUE TITLE
6. Let's Watch: Cues and Visuals in Action

### ISSUE THREAD

**Issue by psjiranek** [kneesen22/Deeper_Dive#41]
Since the ITP headings talk about Use Cues and Visuals to Support...shouldn't each sentence below the examples include the word "cues" as seen under Regulate below? The other 2 only have "use visuals..."

Core Skill: Regulate
Regulate icon
Educators can use cues and visuals 

Core Skill: Move
Move Icon
Educators can use visuals 

Core Skill: Regulate
Regulate icon
Educators can use visuals 

https://educationvirginia.instructure.com/courses/13526/pages/6-lets-watch-cues-and-visuals-in-action?module_item_id=398970

**Comment by kneesen22** [comment]
addressed, although required some rewriting of the text....
