### ISSUE TITLE
End of M2

### ISSUE THREAD

**Issue by psjiranek** [kneesen22/Deeper_Dive#44]
Just a reminder to update this when M3 is ready!

End of Module 2
You have completed module 2!
You can stop here or click the next button below to dive deeper into module 3. Please Note** - Module 3 is in the works so you will not be able to access these just quite yet. If you click next, you'll be routed to module 4 for now.

https://educationvirginia.instructure.com/courses/13526/pages/end-of-module-2?module_item_id=398818

**Comment by kneesen22** [comment]
fixed
