### ISSUE TITLE
M4 1. FOCUS: The Core Skill Focus of the Week Framework

### ISSUE THREAD

**Issue by psjiranek** [kneesen22/Deeper_Dive#45]
Where it fits in the weekly routine?

In the Infant/Toddler curriculum, Focus occurs on Tuesday and can extend into Wednesday. This can include two different Focus ITPs, or provide guidance to expand upon one ITP.

https://educationvirginia.instructure.com/courses/13526/pages/1-focus-the-core-skill-focus-of-the-week-framework

**Comment by kneesen22** [comment]
done
