### ISSUE TITLE
M2 4. Let's Watch: Making Effective Observations

### ISSUE THREAD

**Issue by psjiranek** [kneesen22/Deeper_Dive#46]
Review the [Infant/Toddler Core Skill Summary Sheet](https://educationvirginia.instructure.com/courses/13526/files/1334471?wrap=1)

Infant/Toddler: Cooking in the Kitchen

https://educationvirginia.instructure.com/courses/13526/pages/4-lets-watch-making-effective-observations?module_item_id=394518

**Comment by kneesen22** [comment]
fixed
