### ISSUE TITLE
M6: 1. Scaffold: Quick Recap and Next Steps

### ISSUE THREAD

**Issue by psjiranek** [kneesen22/Deeper_Dive#50]
This sentence needs a rewrite (2 provides & 2 support/s) but I will leave it to your expertise!

We use Scaffold ITPs to provide support and provide feedback that supports children in their development of Core Skills.

https://educationvirginia.instructure.com/courses/13526/pages/1-scaffold-quick-recap-and-next-steps?module_item_id=401404

**Comment by kneesen22** [comment]
The sentence above seems to encapsulate this idea as well so I removed it..will check with Stephanie W and Autumn
