### ISSUE TITLE
1. Scaffold: Quick Recap and Next Steps

### ISSUE THREAD

**Issue by psjiranek** [kneesen22/Deeper_Dive#51]
There's some overlapping of the graphics/text boxes at the bottom of this page.

https://educationvirginia.instructure.com/courses/13526/pages/1-scaffold-quick-recap-and-next-steps?module_item_id=401404

**Comment by kneesen22** [comment]
Stephanie, when this stacks in a responsive way for a smaller page..the text in the top box flow over the image....see screenshot..I can take a look at this for you if you want but will assign to you for now.
<img width="763" alt="Screen Shot 2022-12-07 at 3 19 33 PM" src="https://user-images.githubusercontent.com/2520615/206287120-59db73a4-3217-4a04-b1fa-1e26bc41d09e.png">
<img width="479" alt="Screen Shot 2022-12-07 at 3 19 27 PM" src="https://user-images.githubusercontent.com/2520615/206287131-9c92297f-7c1b-4768-94c0-24889b79b046.png">

**Comment by kneesen22** [comment]
Stephanie, I think this is happening because of the fixed width and height on the DIV inside of the div columns, but normally these DIVs should stack...happy to check this if it's not cooperating.

**Comment by walkersb2** [comment]
@kneesen22 I think it's resolved now if you want to take a look.

**Comment by walkersb2** [comment]
@kneesen22 Never mind. I kind of fixed it, but when I make the browser even smaller, they overlap again. I do think it's because I have the height fixed; however, if I remove the height parameters, then the boxes are lop-sided and different sizes. Do you have any solutions?

**Comment by walkersb2** [comment]
I think I got it as close as I can get it.
