### ISSUE TITLE
M6: 6. You Explore: Scaffold ITPs Across the Core Skills

### ISSUE THREAD

**Issue by psjiranek** [kneesen22/Deeper_Dive#52]
1. In the text box, the ITP becomes "Ask Questions" twice when it had been "Asking Questions" throughout. Can those be changed to say "Asking"?  Same for "Promoting Autonomy" and "Promote Autonomy"

About the ITP Ask Questions | 
Some instances of the ITP Ask Questions...

Same for About the ITP Promote Autonomy
Some instances of the ITP Promote Autonomy include...

2. Can the headings in text boxes have the name of the ITP on the second line (as it is for Promoting (once it's updated from Promote) Autonomy)?

https://educationvirginia.instructure.com/courses/13526/pages/6-you-explore-scaffold-itps-across-the-core-skills?module_item_id=399051

**Comment by kneesen22** [comment]
Ask questions and Promote Autonomy are the official names...it is okay to use both asking questions or ask question...promoting autonomy or promote autonomy.
