### ISSUE TITLE
4. Case Study #1: Keep It Going (Preschool)

### ISSUE THREAD

**Issue by psjiranek** [kneesen22/Deeper_Dive#63]
4. Case Study #1: Keep It Going (Preschool)

The PDF links are NOT separate tabs on this page.

https://educationvirginia.instructure.com/courses/13526/pages/4-case-study-number-1-keep-it-going-preschool?module_item_id=402532

**Comment by kneesen22** [comment]
doesn't work within the LMS context. files are either opened into the files section or downloadable, but can't open files within the LMS files system into new tab.
