### ISSUE TITLE
4. Case Study #1: Keep It Going (Preschool)

### ISSUE THREAD

**Issue by psjiranek** [kneesen22/Deeper_Dive#64]
Capitalization in the entries below seems random? Also is the period on the last one needed and/or should they all have periods?

Day of the Week | Component | Description of Action
-- | -- | --
Observe | Observe children demonstrating the skill across the day
Focus | Label and Describe Various Units of Sound
Scaffold | Commented and Asked Questions on Similarities/Differences in Sound Patterns
Scaffold | Prompted Children to Identify or Manipulate Various Units of Sound
Keep It Going | See below how Ms. Lauren plans to keep things going.

https://educationvirginia.instructure.com/courses/13526/pages/4-case-study-number-1-keep-it-going-preschool?module_item_id=402532

**Comment by kneesen22** [comment]
included ITP to indicate ITPs that are capitalized...removed periods
