### ISSUE TITLE
M7 5. Case Study #2: Keep It Going (Infant)

### ISSUE THREAD

**Issue by psjiranek** [kneesen22/Deeper_Dive#65]
Capitalization and punctuation seem inconsistent in these (as on the page before):

Recap of This Week's Subskill: Teacher-Child Relationships

Day of the Week | Component | Description of Action
-- | -- | --
Observe | Observe children demonstrating the skill across the day.
Focus | Help Children See You as a Resource
Scaffold | Promote Child Autonomy
Keep It Going | See below how Ms. Stephanie plans to keep things going.
Keep It Going | See below how Ms. Stephanie plans to keep things going.

https://educationvirginia.instructure.com/courses/13526/pages/5-case-study-number-2-keep-it-going-infant?module_item_id=402857

**Comment by kneesen22** [comment]
removed periods and made capitalization consistent.
