### ISSUE TITLE
M7 5. Case Study #2: Keep It Going (Infant)

### ISSUE THREAD

**Issue by psjiranek** [kneesen22/Deeper_Dive#66]
links on the page do not open in separate tabs

https://educationvirginia.instructure.com/courses/13526/pages/5-case-study-number-2-keep-it-going-infant?module_item_id=402857

**Comment by kneesen22** [comment]
doesn't work within the LMS context. files are either opened into the files section or downloadable, but can't open files within the LMS files system into new tab.
