### ISSUE TITLE
M7 6. Your Turn: The ECE Resource Hub

### ISSUE THREAD

**Issue by psjiranek** [kneesen22/Deeper_Dive#67]
Step 6/6

Which of the following videos on the Strategy page would you most recommend that Ms. Kathy watch based on her observations?

There are 4 numbered videos listed on the Strategy page (the links don't work to watch them here but not sure they're supposed to?) but only 3 video options in the answer section so I think it needs to be stated that they are choosing from among the 3 numbered "Scenario" videos.

Scenario 1: Sharing Trains

Scenario 2: Taking Turns

Scenario 3: Trading Chairs

https://educationvirginia.instructure.com/courses/13526/quizzes/28290/take/questions/287874?preview=true

**Comment by sarahlydic** [comment]
Added word "Scenario"
