### ISSUE TITLE
M7 6. Your Turn: The ECE Resource Hub

### ISSUE THREAD

**Issue by psjiranek** [kneesen22/Deeper_Dive#68]
the 6 labeled steps with 3 questions amidst them was a little confusing to me, i.e.m Step 2/6 was Q1 but Step 3/6 wasn't Q2? 

https://educationvirginia.instructure.com/courses/13526/quizzes/28290?preview=1

**Comment by sarahlydic** [comment]
No way to relabel the "question" field in Canvas so took out the "Step" labels.
