### ISSUE TITLE
M8 2. Let's Hear From the Field: Using Formative Assessments

### ISSUE THREAD

**Issue by psjiranek** [kneesen22/Deeper_Dive#77]
2. Let's Hear From the Field: Using Formative Assessments
In this short lesson, we'll hear from two STREAMin3 representatives talk about the value of formative assessments.

Either "we'll hear from two STREAMin3 representatives WHO talk about" OR "we'll hear two STREAMin3 representatives talk..."? 

https://educationvirginia.instructure.com/courses/13526/pages/2-lets-hear-from-the-field-using-formative-assessments?module_item_id=400683

**Comment by kneesen22** [comment]
switched to latter option
