### ISSUE TITLE
M8 5. You Explore: The Formative Assessment Family Letter

### ISSUE THREAD

**Issue by psjiranek** [kneesen22/Deeper_Dive#78]
5. You Explore: The Formative Assessment Family Letter

In this short lesson, you’ll have the opportunity to review two Formative Assessment Family Letters.

The Formative Assessment Letter:

should it also include Family in the heading above?

https://educationvirginia.instructure.com/courses/13526/pages/5-you-explore-the-formative-assessment-family-letter?module_item_id=402529

**Comment by kneesen22** [comment]
Yes..good catch
