### ISSUE TITLE
M8 5. You Explore: The Formative Assessment Family Letter

### ISSUE THREAD

**Issue by psjiranek** [kneesen22/Deeper_Dive#79]
Formative Assessment Family Letter: Preschool
Download an example Formative Assessment Family Letter written by an educator who supports preschoolers.

the PDF doesn't say "Preschool" at the top the way the Infant letter does, in case it can be added?

https://educationvirginia.instructure.com/courses/13526/pages/5-you-explore-the-formative-assessment-family-letter?module_item_id=402529

**Comment by kneesen22** [comment]
I believe this is in the PDF itself from the curriculum, so not something we're able to adjust.
