### ISSUE TITLE
M7 1. Keep It Going - What, Why, How

### ISSUE THREAD

**Issue by psjiranek** [kneesen22/Deeper_Dive#84]
A review of the Core Skill Focus of the Week routine.
What Keep It Going is all about and why it is important.
How it connects to the Core Skill Focus of the Week Routine.

Routine is capitalized in bullet point #3 but not #1. I think it should be Routine, right?!
also I'm never sure when we want to use the acronym CSFOW?

https://educationvirginia.instructure.com/courses/13526/pages/3-streamin3-resources-you-can-use?module_item_id=402528

**Comment by kneesen22** [comment]
Routine should not be capitalized..the acronyms is CSFOW (Core Skill Focus of the Week)...and routine or guide after that should not be capitalized. I updated accordingly.
