### ISSUE TITLE
M8 1. An Introduction to Formative Assessments

### ISSUE THREAD

**Issue by psjiranek** [kneesen22/Deeper_Dive#85]
What formative assessments are and why they are important.
How STREAMin3 uses formative assessments.
How the Core Skill Focus of the Week (CSFOW) routine

not sure here about (CSFOW) routine capitalization (this relates to the issue I just submitted from M7) and inconsistent use of acronym?

https://educationvirginia.instructure.com/courses/13526/pages/1-an-introduction-to-formative-assessments

**Comment by kneesen22** [comment]
should be just Core Skill Focus of the Week (CSFOW) and then routine is not capitalized...
