### ISSUE TITLE
M8 4. Let's Plan Together: Using Formative Assessments

### ISSUE THREAD

**Issue by psjiranek** [kneesen22/Deeper_Dive#87]
Part 1: Indentifying Trends from Assessment Data
Here is some of the information that Ashley gathered while assessing the 8 children in their class for the Core Skill Communicate. 
Tip: This information is displayed visually on the Formative Assessment Summary Sheet highlted in the last activity. 

And further down the page:
Identify the trend that accurately reflects the information Ashley gathered. 

1. I'm unable to edit the text box but Indentifying & highlted need correcting!
2. the name is "Ashely" everywhere else on the page but above (it's Ashley twice); definitely the more common spelling? The same Ashley/Ashely issues are in the linked document too.

https://educationvirginia.instructure.com/courses/13526/pages/4-lets-plan-together-using-formative-assessments/edit

**Comment by sarahlydic** [comment]
Corrected "highlighted" and "identify." Changed all instances of Ashley to Ashely in activity and linked doc (less common but consistent w/ previous activity).
